language: ruby
rvm:
  - 1.9.3

#branches:
#  only:
#    - master

env:
  global:
    - BRANCH=coverity_scan
#  matrix:
#  - env: MATRIX_TEST=true
#  - env: MATRIX_TEST=false

#matrix:
#  include:
#  - branch: matrix

script:
  - if [ \"$TRAVIS_BRANCH\" == \"#{BRANCH}\" ]; then
  -   echo "on scan branch"
  -   exit 0
  - else
  -   echo "NOT on scan branch"
  -   exit 1
  - fi
