language: ruby
rvm:
  - 1.9.3

branches:
  only:
    - master

env:
  matrix:
  - env: MATRIX_TEST=true
  - env: MATRIX_TEST=false

#matrix:
#  include:
#  - branch: matrix

script:
  - ruby -e "puts 'hello script'"
  - ruby -e "puts %Q{MATRIX_TEST: #{ENV['MATRIX_TEST']}}"
